version: "3"
services:
  external_server:
    build: ./docker/ext
    container_name: external-server
    volumes:
      - ./data/ext:/app
    stdin_open: true
    tty: true
    depends_on:
      - internal_server
    ports:
      - "9090:9090"
    networks:
      backend:
        ipv4_address: 172.22.0.3

  internal_server:
    build: ./docker/int
    container_name: internal-server
    volumes:
      - ./data/int:/app
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.22.0.4

  db:
    build: ./docker/db
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "mysq1_r00t_p4ssw0rd_d0_n0t_cr4ck_th1s"
    volumes:
      - "./data/db/:/docker-entrypoint-initdb.d/"
    command: mysqld --innodb-buffer-pool-size=16M
    networks:
      backend:
        ipv4_address: 172.22.0.5
    
networks:
  backend:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24
